# 网站的基本信息
site:
  tab: ZSX的小站 # 浏览器标签栏上显示的文本
  title: ZSX的小站 # 网站的标题
  description: 钟神秀的博客，记录着我的文章 # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: https://cn.cravatar.com/avatar/0c7c27ac8fef2941c47fd8bcdcb6a403?size=32 # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: pastel # 主题的浅色模式
    dark: night # 主题的深色模式
    code: github-dark-dimmed # 代码块的主题 https://shiki.style/themes
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 首页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: 文章
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 所有文章
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: resource
          text: 资源分享
          href: /blog/category/resource
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: tech
          text: 技术分享
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # 子菜单项配置
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: social
      text: 社交
      href: #
      svg: "mdi:wechat"
      target: _self
      subItems:
        - id: friends
          text: 友链
          href: /friends
          svg: "material-symbols:supervisor-account-outline-rounded"
          target: _self
        - id: pyq
          text: 鱼塘
          href: /pyq
          svg: "tabler:friends"
          target: _self
    - id: more
      text: 更多
      href: #
      svg: "iconoir:more-horiz-circle"
      target: _self
      subItems:
        - id: memos
          text: 微语
          href: /memos
          svg: "mdi:notebook-edit-outline"
          target: _self
        - id: diary
          text: 日记
          href: /diary
          svg: "material-symbols:book"
          target: _self
        - id: albums
          text: 相册
          href: /albums
          svg: "ri:image-2-fill"
          target: _self
        - id: anime
          text: 番剧
          href: /anime
          svg: "mdi:movie-roll"
          target: _self
    - id: contact
      text: 邮箱
      href: "mailto:zsx@zhzsx.cn"
      target: _blank # 在新标签页打开
      svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: 钟神秀 # 用户名
  site: "https://blog.zhzsx.cn/" # 用户的网站链接
  avatar: /avatar.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://qr-pay.kemeow.top/" # 链接
        ariaLabel: Support my work # 图标的可访问性标签
        title: 赞助 # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://github.com/zsxsw"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3546643173477234"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/kemiaojun"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      - href: "https://x.com/zhzsx_me"
        ariaLabel: telegram
        title: telegram
        svg: "ri:telegram-line"
      - href: "https://qm.qq.com/q/6SICgaZ5kY"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line"
  footer:
    social:
      - href: "https://qr-pay.kemeow.top/" # 链接
        ariaLabel: Support my work # 图标的可访问性标签
        title: 赞助 # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://github.com/zsxsw"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3546643173477234"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/kemiaojun"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      - href: "https://x.com/zhzsx_me"
        ariaLabel: telegram
        title: telegram
        svg: "ri:telegram-line"
      - href: "https://qm.qq.com/q/6SICgaZ5kY"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line"
      - href: "https://www.travellings.cn/go-by-clouds.html"
        ariaLabel: travellings
        title: travellings
        svg: "mdi:train"